name: 'Deploy to Posit Connect'
description: 'Deploy content to Posit Connect using with-connect'
inputs:
  connect-license:
    description: 'Posit Connect license key'
    required: true
  connect-version:
    description: 'Posit Connect version to use'
    required: false
    default: '2025.09.0'
  config-file:
    description: 'Path to optional rstudio-connect.gcfg configuration file'
    required: false
  command:
    description: 'Command to run against Connect'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout with-connect
      uses: actions/checkout@v5
      with:
        repository: tdstein/with-connect
        ref: ${{ github.action_ref }}
        path: .with-connect-action
    
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
    
    - name: Install with-connect
      shell: bash
      run: uv pip install --system .with-connect-action
    
    - name: Create license file
      shell: bash
      run: echo "${{ inputs.connect-license }}" > rstudio-connect.lic
    
    - name: Deploy to Connect
      shell: bash
      run: |
        ARGS="--version ${{ inputs.connect-version }}"
        if [ -n "${{ inputs.config-file }}" ]; then
          ARGS="$ARGS --config ${{ inputs.config-file }}"
        fi
        with-connect $ARGS -- ${{ inputs.command }}
