name: 'Deploy to Posit Connect'
description: 'Deploy content to Posit Connect using with-connect'
inputs:
  license:
    description: 'Posit Connect license key'
    required: true
  version:
    description: 'Posit Connect version to use'
    required: false
    default: 'release'
  config-file:
    description: 'Path to optional rstudio-connect.gcfg configuration file'
    required: false
  quiet:
    description: 'Suppress progress indicators during image pull'
    required: false
    default: 'false'
  port:
    description: 'Port to map the Connect container to'
    required: false
    default: '3939'
  env:
    description: 'Environment variables to pass to Docker container (one per line, format: KEY=VALUE)'
    required: false
  command:
    description: 'Command to run against Connect'
    required: true

runs:
  using: composite
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v7

    - name: Install with-connect
      shell: bash
      run: uv tool install ${{ github.action_path }}

    - name: Create license file
      shell: bash
      run: echo "${{ inputs.license }}" > rstudio-connect.lic

    - name: Run command
      shell: bash
      run: |
        ARGS="--version ${{ inputs.version }} --port ${{ inputs.port }}"
        if [ -n "${{ inputs.config-file }}" ]; then
          ARGS="$ARGS --config ${{ inputs.config-file }}"
        fi
        if [ "${{ inputs.quiet }}" = "true" ]; then
          ARGS="$ARGS --quiet"
        fi
        if [ -n "${{ inputs.env }}" ]; then
          while IFS= read -r line; do
            if [ -n "$line" ]; then
              ARGS="$ARGS -e $line"
            fi
          done <<< "${{ inputs.env }}"
        fi
        with-connect $ARGS -- ${{ inputs.command }}
